### ISSUE TITLE
Use WEB_DIRECTORY instead of copying .js files

### ISSUE THREAD

**Issue by ltdrdata** [Smirnov75/ComfyUI-mxToolkit#1]
Current implementation:
https://github.com/Smirnov75/ComfyUI-mxToolkit/blob/35fcc1ea52ed1261e5cc49b83c14decfddda5bb4/__init__.py#L10

With the current implementation method, deleting or deactivating a Custom node leaves behind garbage, which causes problems.

Take a look at this:
https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/2b7a79090c21329ac309f5c16efcdff42d70f4dc/__init__.py#L38

**Comment by Smirnov75** [comment]
Thank you for the advice.
Fixed.
