### ISSUE TITLE
Feature Request : Set value type of Slider

### ISSUE THREAD

**Issue by PrometheusDante** [Smirnov75/ComfyUI-mxToolkit#13]
The Slider nodes get their output type from the input of the node they're connected to I believe, which in case of "Anything Everywhere" nodes doesn't work unfortunately, defaulting to `int` even despite having a `float` value entered. 

Would a tickbox for **int/float** in the properties panel be a possibility? 

Or an auto-check of `value` , `min` , `max` , `step` , `decimals` for any float values. 
Like :

> if val%1 != 0
> out_type = float

Btw. the arrow-key control for the reroutes is really great, very intuitive and smooth! And if arrow-keys could be applied as an alternative control for the currently selected slider node, it'd be a neat feature too!

Thank you for your time!

**Comment by Smirnov75** [comment]
The type of the output variable depends on the value of `decimals`. If it is 0, the output is an `int`; if it is greater than 0, the output is a `float`.

**Comment by PrometheusDante** [comment]
That is not always the case for me. When I start Comfy and load a workflow with an mxslider directly connected to an `Anything Everywhere?` node, with settings that fulfill all criteria to be a float, it can still output an int. I tried reproducing it to take screenshots, but of course it does not dare happen now. 
I really like your node pack and build it into workflows I publish to get more people to check it out, but when I use the `ImpactFloat` node with widget set to input to act as a float type cast it looks really unprofessional😅

I did look at your code and what you say is clearly set like that, but it still manages to happen. Could the `Anything Everywhere?` node cause that somehow?

**Comment by PrometheusDante** [comment]
This is the workflow that managed to produce the error recently, the day after the major Comfy update came out. 
[flux_advanced_v2_1.json](https://github.com/user-attachments/files/16647139/flux_advanced_v2_1.json)
![flux_advanced_v2_workflow_screenshot_cropped](https://github.com/user-attachments/assets/16907feb-415b-4f42-9b8c-3e9db658e996)

But since then it always loaded correctly. No idea if anything was fixed that may have caused it to happen in the first place or if it is influenced by something different entirely. 

That is just the most recent example of it. All cases it ever ocurred in where connections to `"any"/"anything"` kind of inputs and only after just loading in a workflow for the first time after starting Comfy.

So far it seems alright again and I can not reproduce it by force, so I can unfortunately not provide any more helpful insights on that. 
We can close the issue for now and I use the sliders a lot, so if that issue still persists I would report back with screenshots and more helpful info.

**Comment by PrometheusDante** [comment]
Did not encounter this error in a while, so this issue can be considered resolved.

**Comment by OtakuD** [comment]
Unfortunately I still encounter this issue using set/get nodes on load.
![image](https://github.com/user-attachments/assets/b4cbe71c-b2a0-4611-a9d1-c6b88fe40b89)
