### ISSUE TITLE
[Feature Request] Slider 2D Auto Aspect Ratio 

### ISSUE THREAD

**Issue by toyxyz** [Smirnov75/ComfyUI-mxToolkit#20]
Thanks for the great work! 
I don't know if it's possible, but I have a suggestion. 
Slider 2D nodes have a different aspect ratio than the actual size because the canvas is resized to fit the current node size.
It would be very convenient if the aspect ratio could be automatically corrected to fit the entered max size!

![image](https://github.com/user-attachments/assets/f2e407bf-b6d6-4172-94de-3c0f8fe5a052)

**Comment by Smirnov75** [comment]
In earlier versions of the node, the aspect ratio was fixed, but at the users' request, this feature was disabled. There are no plans to bring it back. It's quite easy to set an approximate aspect ratio. And a precise ratio isn't really necessary.
