### ISSUE TITLE
[bug]There is a very serious problem that triggers screen freezes

### ISSUE THREAD

**Issue by hben35096** [Smirnov75/ComfyUI-mxToolkit#22]
If, within a ComfyUI workflow, the mxReroute node is used, then when sharing this workflow with others, the ComfyUI interface may freeze if those users possess the ComfyUI-mxToolkit plugin but are missing one or more nodes from other plugins.

![PixPin_2024-09-26_21-02-09](https://github.com/user-attachments/assets/49c337be-5417-4585-bf1f-85e447a2b728)
![PixPin_2024-09-26_21-01-39](https://github.com/user-attachments/assets/c8526a35-d3b7-4a06-ae8d-e6ae389f6643)

**Comment by Smirnov75** [comment]
Could you provide a sample workflow that encounters such issues?

**Comment by hben35096** [comment]
I tested several different operating environments, and among them, the ComfyUI operation interface did not freeze in the Windows system.

However, in the cloud instances (Linux system), the same situation occurred across different Python environments. I'm not sure if this is due to the Linux system or because it's being used on a cloud server that's causing the issue.

**Comment by hben35096** [comment]
I randomly created a workflow that included the mxReroute node along with nodes from two less commonly used plugins. This was done to meet the following two conditions:

You have installed ComfyUI-mxToolkit.
Your ComfyUI does not have ComfyUI-FluxTrainer or ComfyUI-IC-Light installed, so as to trigger the "missing node warning."

[bugceshi.json](https://github.com/user-attachments/files/17173378/bugceshi.json)

**Comment by Smirnov75** [comment]
I added extra checks. This should stop these errors from happening again.

**Comment by hben35096** [comment]
Very effective, the problem has now been resolved perfectly. Thank you for your efforts.
