### ISSUE TITLE
In the latest ComfyUI frontend, the mxReroute node turns blue

### ISSUE THREAD

**Issue by hben35096** [Smirnov75/ComfyUI-mxToolkit#23]
![PixPin_2024-10-14_01-08-44](https://github.com/user-attachments/assets/17eeb708-8930-48dc-bd54-4fd8b135b056)

Hello, starting from the new frontend v1.2.64, that is from ComfyUI: 614377abd6c018dec4aeb5700c0e203e2f91f9b0
The default state of the mxReroute node is no longer transparent and turns blue.

**Comment by n0valis** [comment]
I can confirm this.

**Comment by Smirnov75** [comment]
The cause of this issue lies in ComfyUI, not in this node. Unfortunately, the latest ComfyUI update broke the ability to set transparency using rgba(x,x,x,x). I made changes to the node that restore the previous visual style, but let me emphasize once again that this is not a node error.

**Comment by hben35096** [comment]
I know this is not the node's fault; the new frontend has changed too many things. Thank you for making the adjustments.

**Comment by n0valis** [comment]
In a master slave relationship it is not about who's fault it is. It is always the slave who hss to follow the master.
Thank you for making the changes.

**Comment by Smirnov75** [comment]
In situations where the master makes stupid mistakes that have nothing to do with product development, the slave loses the motivation to patch up the holes.

**Comment by n0valis** [comment]
understandable
