### ISSUE TITLE
slider 2d stuck at 1024x1024?

### ISSUE THREAD

**Issue by alenknight** [Smirnov75/ComfyUI-mxToolkit#26]
how do I increase the max resolution of the slider2d?  I saw I can manually enter numbers, but when I try to move the slider point around... it maxes out at 1024x1024.  love the node as it's elegant and perfect for workflows... but wish I could increase the size.

![Screenshot 2024-12-05 at 2 00 48 AM](https://github.com/user-attachments/assets/d672e6e4-9f86-4df6-bc51-654427cc01ad)

**Comment by Smirnov75** [comment]
Maximum values are set using the parameters maxX and maxY
<img width="455" alt="Slider2D 2048 2" src="https://github.com/user-attachments/assets/812cae6b-255f-48a3-bd1e-c83d8fb2c4bf">
<img width="179" alt="Slider2D 2048" src="https://github.com/user-attachments/assets/e29fb46e-a039-4a2b-abf7-ed22be7c28fc">

**Comment by alenknight** [comment]
ahhhh I didn't know comfyui could do that!  thanks!  perfect.
