### ISSUE TITLE
Feature request: Option for correct ration mode in 2d slider

### ISSUE THREAD

**Issue by jdamboeck** [Smirnov75/ComfyUI-mxToolkit#4]
![image](https://github.com/Smirnov75/ComfyUI-mxToolkit/assets/20957463/f7b21dd0-2b52-4b95-a36d-4dffdb4b870b)

In the use case of using 2d slider as a resolution slider an ratio accurate display of the grid as an option might be nice.

**Comment by Smirnov75** [comment]
I will think about the best way to do this. For now, you can delete or comment out this line:
https://github.com/Smirnov75/ComfyUI-mxToolkit/blob/f9e01de8750fa3bc84140cf42a4354fb5463366f/js/Slider2D.js#L92
This will allow you to freely change the node size.
In the next version, I might set this mode as the default.

**Comment by Smirnov75** [comment]
The ability to freely change the aspect ratio of the node has been implemented in the latest version.
