### ISSUE TITLE
Entering a value out of range

### ISSUE THREAD

**Issue by DmitryKripakov** [Smirnov75/ComfyUI-mxToolkit#6]
Hello! Thank you so much for the normal sliders, they finally appeared in ComfyUI, you can’t imagine how long I’ve been waiting for this :)

It seems to me that they can be improved a little by adding the ability to manually enter parameter values ​​above the specified min max range, as is done in Houdini or substance designer. It may be possible to leave a field with a value open for editing, or simply force the value not to be limited to a range, so that you can change it manually through the Properties menu.

Well, just as an idea, it would be convenient to have a “Default Value” that can be snapped to while holding Ctrl, just like it is done with Shift, which would also be configured in Properties.

Thank you again!

**Comment by Smirnov75** [comment]
Htllo! Your suggestion for improvement is interesting. Could you please provide more details on situations where setting values beyond specified range is necessary? This will help me find the best and most convenient solution.

**Comment by DmitryKripakov** [comment]
For example, when there is a parameter that in 99% of cases changes in the range from .5 to 1, but sometimes you still need to set it to .1 or 2 for tests or something else. In such cases, you don’t want to sacrifice convenience in the remaining 99% of cases :)

Or, also as an example, I sometimes share my workflow with colleagues, and it is much easier to explain in what range you can change this or that parameter when these ranges are already in the slider. But in rare cases it is also necessary to enter an extreme value.

In the substance designer, the intensity range of the Normal node is from 0 to 3, and the slider turns out to be quite accurate for 80% of cases. But in the remaining 20% ​​you need to enter the values ​​5-10-15-20, etc. If the slider was initially in the range from 0 to 30, then using it in 80% of cases to select small values ​​would be terribly inconvenient.

In Houdini, you can set the ability to separately limit the upper and lower limits of a parameter, for example, to avoid multiplication by zero, but at the same time allow you to go beyond the upper limit of the parameter. But this is overkill)

**Comment by Smirnov75** [comment]
I updated the Slider node:
Disabled min and max value checking to allow manually setting values outside the defined range. This can also be done by pressing a Ctrl key while moving the slider.

**Comment by Smirnov75** [comment]
In the last version I've added the ability to change values by double-clicking on them.

**Comment by abdrahman7** [comment]
Hello world
