### ISSUE TITLE
Slider 2D Suggestion

### ISSUE THREAD

**Issue by DeepSeaCatz** [Smirnov75/ComfyUI-mxToolkit#9]
Love the visual UI of these nodes! I've been converting every width/height widget to input the Slider 2D. I also love the Reroutes direction, kind of like gas lines organizer. I found it a bit long to set it up, but it's perfect for tidying a workflow before sharing it!

I did find 2 things that could be improved. If you quickly grab the node on the top right corner, it'll swap the values instead of letting you grab it. This mixed me once when I didn't pay attention when moving the nodes around.

![image](https://github.com/Smirnov75/ComfyUI-mxToolkit/assets/114247596/262591d0-9219-4e05-933a-4ceb32fe4025)

2nd suggestion would be if it's possible to add a way to input the values instead of going in the properties. Sometimes I do 768x1344 and holding shift doesn't seem to bring it to precision. If it's possible, I was thinking that the values could be selectable and a toggle button could be under to switch w/h values.

Thanks for making this node!

**Comment by Smirnov75** [comment]
Thank you for your feedback. Check the new version.
The first thing was a bug. It has been fixed. Now values can only be swapped when the Shift key is pressed. This will prevent accidental presses. Also added the ability to change values by double-clicking on them.

**Comment by Smirnov75** [comment]
I forgot to mention that when entering manually, you can set a value outside the range. This is not a bug.

**Comment by DeepSeaCatz** [comment]
Awesome! Thanks a lot for the quick update, this now works perfectly! I've shared it with someone else in the community and he's been wishing that same change.
